### ISSUE TITLE
Prompt for password if not supplied

### ISSUE THREAD

**Issue by thenoid** [chef-partners/knife-vrealize#14]
Currently it appears there are two options for hte password

1) specify on the command line (booooo)
2) specify in the knife.rb (lil less booo)

if neither are supplied the plugin errors out with the following

```
chef> knife vra catalog list
ERROR: The following required parameters are missing: vra_password
```

instead it would preferred to prompt the user for the password/credentials

**Comment by adamleff** [comment]
Hi, @thenoid. This is not something we're likely to address as it's not consistent with the way other knife plugins receive the user's credentials. Even the knife-ec2 gem reads the access key ID / secret key from a known file location by default.

A potential solution might be to allow the passing of the data via an environment variable, like you can do with EC2 credentials. I'd happily review a PR, or you can do this yourself in your own knife.rb:

```
knife[:vra_password] = ENV['VRA_PASSWORD']
```

However, since we don't plan to add any credential prompting, I'm going to close out this issue. Thanks!

~Adam

**Comment by thenoid** [comment]
I've encountered some plugins that prompted, but if that isn't the standard, i'm totally okay with it.  Thanks for the feedback.
